package EntityLayer.Ortak;

/**
 * Created by isahin on 30.01.2018.
 */

public class OzetEkranEntity {


    private Long				id;

    public Long getId() {
        return this.id;
    }

    public void setId(final Long id) {
        this.id = id;
    }

    public  Integer	GENEL_OZET_MUHASEBE_NAKIT_DURUMU			= 1;
    public  Integer	GENEL_OZET_MUHASEBE_KASA					= 2;
    public  Integer	GENEL_OZET_MUHASEBE_BANKA					= 3;
    public  Integer	GENEL_OZET_MUHASEBE_TOPLAM_IHALE			= 4;
    public  Integer	GENEL_OZET_MUHASEBE_GERCEKLESEN_IHALE		= 5;

    public  Integer	GENEL_OZET_PAZARLAMA_DIKILI_DAMGA			= 101;
    public  Integer	GENEL_OZET_PAZARLAMA_MAKTA_STOGU			= 102;
    public  Integer	GENEL_OZET_PAZARLAMA_RAMPA_STOGU			= 103;
    public  Integer	GENEL_OZET_PAZARLAMA_SON_DEPO				= 104;

    public  Integer	GENEL_OZET_PERSONEL_MEMUR_SAYISI			= 201;
    public  Integer	GENEL_OZET_PERSONEL_ISCI_SAYISI				= 202;
    public  Integer	GENEL_OZET_PERSONEL_TOPLAM_CALISAN_SAYISI	= 203;

    public  Integer	GENEL_OZET_OZM_MUCADELE_PROJE_SAYISI		= 301;
    public  Integer	GENEL_OZET_OZM_SUC_TUTANAGI_SAYISI			= 302;

    public  Integer	GENEL_OZET_ODUH_MESIRE_YERI_SAYISI			= 401;
    public  Integer	GENEL_OZET_ODUH_BAL_ORMANI_SAYISI			= 402;
    public  Integer	GENEL_OZET_ODUH_TOPLAM_GELIR				= 403;

    public  Integer	GENEL_OZET_IZIN_SAHASI_SAYISI				= 501;
    public  Integer	GENEL_OZET_IZIN_SAHASI_ALANI				= 502;
    public  Integer	GENEL_OZET_IZIN_TAHAKKUKU					= 503;
    public  Integer	GENEL_OZET_IZIN_GELIRI						= 504;

    public  Integer	GENEL_OZET_ORKOY_KOY_SAYISI					= 601;
    public  Integer	GENEL_OZET_ORKOY_KOYLU_SAYISI				= 602;
    public  Integer	GENEL_OZET_ORKOY_PROJE_SAYISI				= 603;
    public  Integer	GENEL_OZET_ORKOY_KREDI_TUTARI				= 604;
    public  Integer	GENEL_OZET_ORKOY_HIBE_TUTARI				= 605;

    public  Integer	GENEL_OZET_YANGIN_DEVAM_EDEN_YANGIN_SAYISI	= 701;
    public  Integer	GENEL_OZET_YANGIN_EKIP_SAYISI				= 702;
    public  Integer	GENEL_OZET_YANGIN_KULE_SAYISI				= 703;
    public  Integer	GENEL_OZET_YANGIN_TUM_YANGIN_SAYISI			= 704;

    public  Integer	GENEL_OZET_HUKUK_DAVA_SAYISI				= 801;
    public  Integer	GENEL_OZET_HUKUK_DAVA_TUTARI				= 802;
    public  Integer	GENEL_OZET_HUKUK_ICRA_SAYISI				= 803;
    public  Integer	GENEL_OZET_HUKUK_ICRA_TUTARI				= 804;

    public Integer	GENEL_OZET_TASINMAZ_YAPI_SAYISI				= 901;
    public Integer	GENEL_OZET_TASINMAZ_PARSEL_SAYISI			= 902;
    public Integer	GENEL_OZET_TASINMAZ_TESIS_SAYISI			= 903;
    public Integer	GENEL_OZET_TASINMAZ_ARAC_SAYISI				= 904;

    public Integer getGENEL_OZET_MUHASEBE_NAKIT_DURUMU() {
        return GENEL_OZET_MUHASEBE_NAKIT_DURUMU;
    }

    public void setGENEL_OZET_MUHASEBE_NAKIT_DURUMU(Integer GENEL_OZET_MUHASEBE_NAKIT_DURUMU) {
        this.GENEL_OZET_MUHASEBE_NAKIT_DURUMU = GENEL_OZET_MUHASEBE_NAKIT_DURUMU;
    }

    public Integer getGENEL_OZET_MUHASEBE_KASA() {
        return GENEL_OZET_MUHASEBE_KASA;
    }

    public void setGENEL_OZET_MUHASEBE_KASA(Integer GENEL_OZET_MUHASEBE_KASA) {
        this.GENEL_OZET_MUHASEBE_KASA = GENEL_OZET_MUHASEBE_KASA;
    }

    public Integer getGENEL_OZET_MUHASEBE_BANKA() {
        return GENEL_OZET_MUHASEBE_BANKA;
    }

    public void setGENEL_OZET_MUHASEBE_BANKA(Integer GENEL_OZET_MUHASEBE_BANKA) {
        this.GENEL_OZET_MUHASEBE_BANKA = GENEL_OZET_MUHASEBE_BANKA;
    }

    public Integer getGENEL_OZET_MUHASEBE_TOPLAM_IHALE() {
        return GENEL_OZET_MUHASEBE_TOPLAM_IHALE;
    }

    public void setGENEL_OZET_MUHASEBE_TOPLAM_IHALE(Integer GENEL_OZET_MUHASEBE_TOPLAM_IHALE) {
        this.GENEL_OZET_MUHASEBE_TOPLAM_IHALE = GENEL_OZET_MUHASEBE_TOPLAM_IHALE;
    }

    public Integer getGENEL_OZET_MUHASEBE_GERCEKLESEN_IHALE() {
        return GENEL_OZET_MUHASEBE_GERCEKLESEN_IHALE;
    }

    public void setGENEL_OZET_MUHASEBE_GERCEKLESEN_IHALE(Integer GENEL_OZET_MUHASEBE_GERCEKLESEN_IHALE) {
        this.GENEL_OZET_MUHASEBE_GERCEKLESEN_IHALE = GENEL_OZET_MUHASEBE_GERCEKLESEN_IHALE;
    }

    public Integer getGENEL_OZET_PAZARLAMA_DIKILI_DAMGA() {
        return GENEL_OZET_PAZARLAMA_DIKILI_DAMGA;
    }

    public void setGENEL_OZET_PAZARLAMA_DIKILI_DAMGA(Integer GENEL_OZET_PAZARLAMA_DIKILI_DAMGA) {
        this.GENEL_OZET_PAZARLAMA_DIKILI_DAMGA = GENEL_OZET_PAZARLAMA_DIKILI_DAMGA;
    }

    public Integer getGENEL_OZET_PAZARLAMA_MAKTA_STOGU() {
        return GENEL_OZET_PAZARLAMA_MAKTA_STOGU;
    }

    public void setGENEL_OZET_PAZARLAMA_MAKTA_STOGU(Integer GENEL_OZET_PAZARLAMA_MAKTA_STOGU) {
        this.GENEL_OZET_PAZARLAMA_MAKTA_STOGU = GENEL_OZET_PAZARLAMA_MAKTA_STOGU;
    }

    public Integer getGENEL_OZET_PAZARLAMA_RAMPA_STOGU() {
        return GENEL_OZET_PAZARLAMA_RAMPA_STOGU;
    }

    public void setGENEL_OZET_PAZARLAMA_RAMPA_STOGU(Integer GENEL_OZET_PAZARLAMA_RAMPA_STOGU) {
        this.GENEL_OZET_PAZARLAMA_RAMPA_STOGU = GENEL_OZET_PAZARLAMA_RAMPA_STOGU;
    }

    public Integer getGENEL_OZET_PAZARLAMA_SON_DEPO() {
        return GENEL_OZET_PAZARLAMA_SON_DEPO;
    }

    public void setGENEL_OZET_PAZARLAMA_SON_DEPO(Integer GENEL_OZET_PAZARLAMA_SON_DEPO) {
        this.GENEL_OZET_PAZARLAMA_SON_DEPO = GENEL_OZET_PAZARLAMA_SON_DEPO;
    }

    public Integer getGENEL_OZET_PERSONEL_MEMUR_SAYISI() {
        return GENEL_OZET_PERSONEL_MEMUR_SAYISI;
    }

    public void setGENEL_OZET_PERSONEL_MEMUR_SAYISI(Integer GENEL_OZET_PERSONEL_MEMUR_SAYISI) {
        this.GENEL_OZET_PERSONEL_MEMUR_SAYISI = GENEL_OZET_PERSONEL_MEMUR_SAYISI;
    }

    public Integer getGENEL_OZET_PERSONEL_ISCI_SAYISI() {
        return GENEL_OZET_PERSONEL_ISCI_SAYISI;
    }

    public void setGENEL_OZET_PERSONEL_ISCI_SAYISI(Integer GENEL_OZET_PERSONEL_ISCI_SAYISI) {
        this.GENEL_OZET_PERSONEL_ISCI_SAYISI = GENEL_OZET_PERSONEL_ISCI_SAYISI;
    }

    public Integer getGENEL_OZET_PERSONEL_TOPLAM_CALISAN_SAYISI() {
        return GENEL_OZET_PERSONEL_TOPLAM_CALISAN_SAYISI;
    }

    public void setGENEL_OZET_PERSONEL_TOPLAM_CALISAN_SAYISI(Integer GENEL_OZET_PERSONEL_TOPLAM_CALISAN_SAYISI) {
        this.GENEL_OZET_PERSONEL_TOPLAM_CALISAN_SAYISI = GENEL_OZET_PERSONEL_TOPLAM_CALISAN_SAYISI;
    }

    public Integer getGENEL_OZET_OZM_MUCADELE_PROJE_SAYISI() {
        return GENEL_OZET_OZM_MUCADELE_PROJE_SAYISI;
    }

    public void setGENEL_OZET_OZM_MUCADELE_PROJE_SAYISI(Integer GENEL_OZET_OZM_MUCADELE_PROJE_SAYISI) {
        this.GENEL_OZET_OZM_MUCADELE_PROJE_SAYISI = GENEL_OZET_OZM_MUCADELE_PROJE_SAYISI;
    }

    public Integer getGENEL_OZET_OZM_SUC_TUTANAGI_SAYISI() {
        return GENEL_OZET_OZM_SUC_TUTANAGI_SAYISI;
    }

    public void setGENEL_OZET_OZM_SUC_TUTANAGI_SAYISI(Integer GENEL_OZET_OZM_SUC_TUTANAGI_SAYISI) {
        this.GENEL_OZET_OZM_SUC_TUTANAGI_SAYISI = GENEL_OZET_OZM_SUC_TUTANAGI_SAYISI;
    }

    public Integer getGENEL_OZET_ODUH_MESIRE_YERI_SAYISI() {
        return GENEL_OZET_ODUH_MESIRE_YERI_SAYISI;
    }

    public void setGENEL_OZET_ODUH_MESIRE_YERI_SAYISI(Integer GENEL_OZET_ODUH_MESIRE_YERI_SAYISI) {
        this.GENEL_OZET_ODUH_MESIRE_YERI_SAYISI = GENEL_OZET_ODUH_MESIRE_YERI_SAYISI;
    }

    public Integer getGENEL_OZET_ODUH_BAL_ORMANI_SAYISI() {
        return GENEL_OZET_ODUH_BAL_ORMANI_SAYISI;
    }

    public void setGENEL_OZET_ODUH_BAL_ORMANI_SAYISI(Integer GENEL_OZET_ODUH_BAL_ORMANI_SAYISI) {
        this.GENEL_OZET_ODUH_BAL_ORMANI_SAYISI = GENEL_OZET_ODUH_BAL_ORMANI_SAYISI;
    }

    public Integer getGENEL_OZET_ODUH_TOPLAM_GELIR() {
        return GENEL_OZET_ODUH_TOPLAM_GELIR;
    }

    public void setGENEL_OZET_ODUH_TOPLAM_GELIR(Integer GENEL_OZET_ODUH_TOPLAM_GELIR) {
        this.GENEL_OZET_ODUH_TOPLAM_GELIR = GENEL_OZET_ODUH_TOPLAM_GELIR;
    }

    public Integer getGENEL_OZET_IZIN_SAHASI_SAYISI() {
        return GENEL_OZET_IZIN_SAHASI_SAYISI;
    }

    public void setGENEL_OZET_IZIN_SAHASI_SAYISI(Integer GENEL_OZET_IZIN_SAHASI_SAYISI) {
        this.GENEL_OZET_IZIN_SAHASI_SAYISI = GENEL_OZET_IZIN_SAHASI_SAYISI;
    }

    public Integer getGENEL_OZET_IZIN_SAHASI_ALANI() {
        return GENEL_OZET_IZIN_SAHASI_ALANI;
    }

    public void setGENEL_OZET_IZIN_SAHASI_ALANI(Integer GENEL_OZET_IZIN_SAHASI_ALANI) {
        this.GENEL_OZET_IZIN_SAHASI_ALANI = GENEL_OZET_IZIN_SAHASI_ALANI;
    }

    public Integer getGENEL_OZET_IZIN_TAHAKKUKU() {
        return GENEL_OZET_IZIN_TAHAKKUKU;
    }

    public void setGENEL_OZET_IZIN_TAHAKKUKU(Integer GENEL_OZET_IZIN_TAHAKKUKU) {
        this.GENEL_OZET_IZIN_TAHAKKUKU = GENEL_OZET_IZIN_TAHAKKUKU;
    }

    public Integer getGENEL_OZET_IZIN_GELIRI() {
        return GENEL_OZET_IZIN_GELIRI;
    }

    public void setGENEL_OZET_IZIN_GELIRI(Integer GENEL_OZET_IZIN_GELIRI) {
        this.GENEL_OZET_IZIN_GELIRI = GENEL_OZET_IZIN_GELIRI;
    }

    public Integer getGENEL_OZET_ORKOY_KOY_SAYISI() {
        return GENEL_OZET_ORKOY_KOY_SAYISI;
    }

    public void setGENEL_OZET_ORKOY_KOY_SAYISI(Integer GENEL_OZET_ORKOY_KOY_SAYISI) {
        this.GENEL_OZET_ORKOY_KOY_SAYISI = GENEL_OZET_ORKOY_KOY_SAYISI;
    }

    public Integer getGENEL_OZET_ORKOY_KOYLU_SAYISI() {
        return GENEL_OZET_ORKOY_KOYLU_SAYISI;
    }

    public void setGENEL_OZET_ORKOY_KOYLU_SAYISI(Integer GENEL_OZET_ORKOY_KOYLU_SAYISI) {
        this.GENEL_OZET_ORKOY_KOYLU_SAYISI = GENEL_OZET_ORKOY_KOYLU_SAYISI;
    }

    public Integer getGENEL_OZET_ORKOY_PROJE_SAYISI() {
        return GENEL_OZET_ORKOY_PROJE_SAYISI;
    }

    public void setGENEL_OZET_ORKOY_PROJE_SAYISI(Integer GENEL_OZET_ORKOY_PROJE_SAYISI) {
        this.GENEL_OZET_ORKOY_PROJE_SAYISI = GENEL_OZET_ORKOY_PROJE_SAYISI;
    }

    public Integer getGENEL_OZET_ORKOY_KREDI_TUTARI() {
        return GENEL_OZET_ORKOY_KREDI_TUTARI;
    }

    public void setGENEL_OZET_ORKOY_KREDI_TUTARI(Integer GENEL_OZET_ORKOY_KREDI_TUTARI) {
        this.GENEL_OZET_ORKOY_KREDI_TUTARI = GENEL_OZET_ORKOY_KREDI_TUTARI;
    }

    public Integer getGENEL_OZET_ORKOY_HIBE_TUTARI() {
        return GENEL_OZET_ORKOY_HIBE_TUTARI;
    }

    public void setGENEL_OZET_ORKOY_HIBE_TUTARI(Integer GENEL_OZET_ORKOY_HIBE_TUTARI) {
        this.GENEL_OZET_ORKOY_HIBE_TUTARI = GENEL_OZET_ORKOY_HIBE_TUTARI;
    }

    public Integer getGENEL_OZET_YANGIN_DEVAM_EDEN_YANGIN_SAYISI() {
        return GENEL_OZET_YANGIN_DEVAM_EDEN_YANGIN_SAYISI;
    }

    public void setGENEL_OZET_YANGIN_DEVAM_EDEN_YANGIN_SAYISI(Integer GENEL_OZET_YANGIN_DEVAM_EDEN_YANGIN_SAYISI) {
        this.GENEL_OZET_YANGIN_DEVAM_EDEN_YANGIN_SAYISI = GENEL_OZET_YANGIN_DEVAM_EDEN_YANGIN_SAYISI;
    }

    public Integer getGENEL_OZET_YANGIN_EKIP_SAYISI() {
        return GENEL_OZET_YANGIN_EKIP_SAYISI;
    }

    public void setGENEL_OZET_YANGIN_EKIP_SAYISI(Integer GENEL_OZET_YANGIN_EKIP_SAYISI) {
        this.GENEL_OZET_YANGIN_EKIP_SAYISI = GENEL_OZET_YANGIN_EKIP_SAYISI;
    }

    public Integer getGENEL_OZET_YANGIN_KULE_SAYISI() {
        return GENEL_OZET_YANGIN_KULE_SAYISI;
    }

    public void setGENEL_OZET_YANGIN_KULE_SAYISI(Integer GENEL_OZET_YANGIN_KULE_SAYISI) {
        this.GENEL_OZET_YANGIN_KULE_SAYISI = GENEL_OZET_YANGIN_KULE_SAYISI;
    }

    public Integer getGENEL_OZET_YANGIN_TUM_YANGIN_SAYISI() {
        return GENEL_OZET_YANGIN_TUM_YANGIN_SAYISI;
    }

    public void setGENEL_OZET_YANGIN_TUM_YANGIN_SAYISI(Integer GENEL_OZET_YANGIN_TUM_YANGIN_SAYISI) {
        this.GENEL_OZET_YANGIN_TUM_YANGIN_SAYISI = GENEL_OZET_YANGIN_TUM_YANGIN_SAYISI;
    }

    public Integer getGENEL_OZET_HUKUK_DAVA_SAYISI() {
        return GENEL_OZET_HUKUK_DAVA_SAYISI;
    }

    public void setGENEL_OZET_HUKUK_DAVA_SAYISI(Integer GENEL_OZET_HUKUK_DAVA_SAYISI) {
        this.GENEL_OZET_HUKUK_DAVA_SAYISI = GENEL_OZET_HUKUK_DAVA_SAYISI;
    }

    public Integer getGENEL_OZET_HUKUK_DAVA_TUTARI() {
        return GENEL_OZET_HUKUK_DAVA_TUTARI;
    }

    public void setGENEL_OZET_HUKUK_DAVA_TUTARI(Integer GENEL_OZET_HUKUK_DAVA_TUTARI) {
        this.GENEL_OZET_HUKUK_DAVA_TUTARI = GENEL_OZET_HUKUK_DAVA_TUTARI;
    }

    public Integer getGENEL_OZET_HUKUK_ICRA_SAYISI() {
        return GENEL_OZET_HUKUK_ICRA_SAYISI;
    }

    public void setGENEL_OZET_HUKUK_ICRA_SAYISI(Integer GENEL_OZET_HUKUK_ICRA_SAYISI) {
        this.GENEL_OZET_HUKUK_ICRA_SAYISI = GENEL_OZET_HUKUK_ICRA_SAYISI;
    }

    public Integer getGENEL_OZET_HUKUK_ICRA_TUTARI() {
        return GENEL_OZET_HUKUK_ICRA_TUTARI;
    }

    public void setGENEL_OZET_HUKUK_ICRA_TUTARI(Integer GENEL_OZET_HUKUK_ICRA_TUTARI) {
        this.GENEL_OZET_HUKUK_ICRA_TUTARI = GENEL_OZET_HUKUK_ICRA_TUTARI;
    }

    public Integer getGENEL_OZET_TASINMAZ_YAPI_SAYISI() {
        return GENEL_OZET_TASINMAZ_YAPI_SAYISI;
    }

    public void setGENEL_OZET_TASINMAZ_YAPI_SAYISI(Integer GENEL_OZET_TASINMAZ_YAPI_SAYISI) {
        this.GENEL_OZET_TASINMAZ_YAPI_SAYISI = GENEL_OZET_TASINMAZ_YAPI_SAYISI;
    }

    public Integer getGENEL_OZET_TASINMAZ_PARSEL_SAYISI() {
        return GENEL_OZET_TASINMAZ_PARSEL_SAYISI;
    }

    public void setGENEL_OZET_TASINMAZ_PARSEL_SAYISI(Integer GENEL_OZET_TASINMAZ_PARSEL_SAYISI) {
        this.GENEL_OZET_TASINMAZ_PARSEL_SAYISI = GENEL_OZET_TASINMAZ_PARSEL_SAYISI;
    }

    public Integer getGENEL_OZET_TASINMAZ_TESIS_SAYISI() {
        return GENEL_OZET_TASINMAZ_TESIS_SAYISI;
    }

    public void setGENEL_OZET_TASINMAZ_TESIS_SAYISI(Integer GENEL_OZET_TASINMAZ_TESIS_SAYISI) {
        this.GENEL_OZET_TASINMAZ_TESIS_SAYISI = GENEL_OZET_TASINMAZ_TESIS_SAYISI;
    }

    public Integer getGENEL_OZET_TASINMAZ_ARAC_SAYISI() {
        return GENEL_OZET_TASINMAZ_ARAC_SAYISI;
    }

    public void setGENEL_OZET_TASINMAZ_ARAC_SAYISI(Integer GENEL_OZET_TASINMAZ_ARAC_SAYISI) {
        this.GENEL_OZET_TASINMAZ_ARAC_SAYISI = GENEL_OZET_TASINMAZ_ARAC_SAYISI;
    }
}
